import Head from "next/head";
import Header from "@/components/layouts/Header";
import SearchBar from "@/components/SearchBar";
import study_areas_data from "@/data/study_areas_data";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="max-w-lg mx-auto flex flex-col justify-center px-5">
        <SearchBar data={study_areas_data} />
      </main>
    </>
  );
}
