import Head from "next/head";
import Header from "@/components/layouts/Header";

import ButtonPack from "@/components/ButtonPack";

import SAinfoCard from "@/components/SAinfoCard";
import study_areas_data from "../data/study_areas_data";
import type { StudyAreaInfoCard } from '@/components/SAinfoCard'


export default function UpdateStudyArea() {

let cards: any = []

study_areas_data.forEach((area: StudyAreaInfoCard) => {
  cards.push(<SAinfoCard {...area} />);
});

  return (
  <>
    <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
    <Header />
    <main>
      <section>{cards}</section>
      <ButtonPack />
    </main>
  </>
  );
}